version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: assessly-db-prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - assessly-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: assessly-backend-prod
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - assessly-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assessly-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - assessly-network
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/ssl/certs:ro
    environment:
      - VITE_API_BASE_URL=https://assessly.website
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  assessly-network:
    driver: bridge

volumes:
  postgres_data_prod:
 